# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanRxSwift
  pod 'Alamofire', '~> 4.7'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'CleanRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanRxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
